### ISSUE TITLE
Bioconda Install Error: Unsatisfiable Error

### ISSUE THREAD

**Issue by CCranney** [althonos/pyhmmer#11]
I'm trying to download pyhmmer via bioconda with this line:

`conda install -c bioconda pyhmmer`

 but I keep getting the following error:

UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions

Notably, it fails to list/provide detail for what specifications were incompatible. I've tried doing it in previous python versions in case that impacts it, but I get the same error for every version above 3.5. I asked another friend of mine to attempt the install because my computer is a mac from early 2014 on outdated software (Catalina 10.15.7), but he too ran into the error.

The pip install largely works and I'm trying to work through that for now, but do you know if this error has appeared among other users and if a fix exists?

**Comment by althonos** [comment]
Hi Caleb, 

This is a first time seeing this, given I'm not developing on a Mac I don't get to see these errors but even my colleagues didn't seem to encounter that issue when installing `pyhmmer` or dependent software.

Could you please give me the whole `UnsatisfiableError` traceback? `pyhmmer` has a single runtime dependency so maybe I could relax the version of that package if it helps installing on older machines. Since it works with `pip` I'd guess something is wrong in the bioconda recipe itself.

**Comment by althonos** [comment]
Hi @CCranney , is this error still happening? Have you tried updating `conda` itself? I don't think I have a fix to offer because I've never seen this error, it looks like a `conda` bug more like a `pyhmmer` bug to me, but I'm not sure what could be the cause.

**Comment by CCranney** [comment]
Hi @althonos! I worked with my team on a different approach and therefore are no longer using `pyhmmer`, so I don't recall if we resolved this issue before we changed strategies.
