### ISSUE TITLE
Reported/Included domain counts are doubled after TopHits merge

### ISSUE THREAD

**Issue by zdk123** [althonos/pyhmmer#46]
To replicate:
```py
thioesterase = HMMFile("tests/data/hmms/db/Thioesterase.hmm").read()

with SequenceFile('tests/data/seqs/938293.PRJEB85.HG003687.faa', digital=True) as seqfile:
    proteins = seqfile.read_block()
pli = Pipeline(thioesterase.alphabet, T=1, domT=1, incT=1, incdomT=1)
hits1 = pli.search_hmm(thioesterase, proteins[:1000],)
hits2 = pli.search_hmm(thioesterase, proteins[1000:2000])
hits3 = pli.search_hmm(thioesterase, proteins[2000:])
merged = hits1.merge(hits2, hits3)

with open("test.tblout", "wb") as f:
    merged.write(f, format="targets")
with open("test.domtblout", "wb") as f:
    merged.write(f, format="domains")
```

If you inspect the target table you see the following reported for domain number estimation for the hit 938293.PRJEB85.HG003687_113:
```
exp reg clu  ov env dom rep inc
--- --- --- --- --- --- --- ---
1.2   1   0   0   1   1   2   2
```

the rep/inc count is double than what is expected. The counts are correct when including all proteins and without merging

**Comment by althonos** [comment]
Good catch, this is indeed a bug in HMMER that we should report and fix: 

In `p7_tophits_Threshold` the hits counts are reset:

https://github.com/EddyRivasLab/hmmer/blob/03bf3c7767233e45cb969bfeda910545b80f2da8/src/p7_tophits.c#L899-L905

but the domain counts are not reset:

https://github.com/EddyRivasLab/hmmer/blob/master/src/p7_tophits.c#L935-L941

**Comment by althonos** [comment]
Ok this should be fixed! I actually also had some failing tests that were checking for the wrong thing :see_no_evil: 

Now `TopHits.merge` will do a full copy / initialization if called on an empty instance, which will fix the problem of inconsistent reporting thresholds. And afterwards one has to reset the `flags` of each `P7_HIT` before calling `p7_tophits_Threshold`, otherwise domain counts would not be reset even after a change in `Z` or `domZ` in the merged pipeline.
