### ISSUE TITLE
Scoring a set of sequences with HMM

### ISSUE THREAD

**Issue by paoslaos** [althonos/pyhmmer#55]
Thanks for this great library! I just started recently to dig into using HMMs so my question is very very basic. I have build an HMM from an alignment to a specific protein family, now I want to use the HMM to score a list of other protein sequences (*all of them*).

I tried using the TraceAligner with something like this because hmmalign() would not give the desired metrics (?):

```python
    seq_block = pyhmmer.easel.DigitalSequenceBlock(alphabet, seq)
    aligner = pyhmmer.plan7.TraceAligner(posteriors=True)
    traces = aligner.compute_traces(hmm=hmm, sequences=seq_block)
    msa = aligner.align_traces(hmm=hmm, sequences=seq_block, traces=traces)
    scores = [trace.expected_accuracy() for trace in traces]
```

Is there an alternative that you recommend to get various alignment scores for my query sequences? I need all of them scored and typically I am interested in alignment scores, e-values, and other easily available metrics.

Great appreciation!

Peace
Paos

**Comment by althonos** [comment]
Hi Paos, sounds like you want to use `hmmsearch` or `hmmscan` here! `hmmalign` is a very specific case where you have a HMM and sequence which you already know belong to the same sequence family, and you want to use the HMM as a guide for aligning all of them. 

Using [`hmmsearch`](https://pyhmmer.readthedocs.io/en/stable/api/hmmer.html#pyhmmer.hmmer.hmmsearch) you will get one [`TopHits`](https://pyhmmer.readthedocs.io/en/stable/api/plan7.html#pyhmmer.plan7.TopHits) object per input HMM, which will summarize the hits it got to all of your sequences databases, including bitscore, *p-value* and *e-values*.

**Comment by althonos** [comment]
> First, I wasnt able to get a score for each of my sequences. It took me a bit to realize the right filtering options because changing E, T didnt seem to do the trick.

Yes exactly, the typical usecase of HMMER is to find some hits for a HMM in a lot of proteins so there are several pre-filtering heuristics to kick out very distant sequences (with a cheaper version of the algorithm) without actually computing scores for the remaining ones. If your last two sequences are quite distant it's very likely they were being kicked by the filter first, unless you disable it as you did.

> For reference, here is my snippet:

In here i'd recommend using `hmmsearch`, it's usually faster, and then you get a single `TopHits` for your query, so extracting the results is easier (something like):
```python
hits = next(pyhmmer.hmmer.hmmscan(hmm_model, hmm_sequences, bias_filter=False, F1=1.0, F2=1.0, F3=1.0)
print("name score evalue pvalue total_n current_n")
for hit in hits:
    print(hit.name, round(hit.score, 2), round(hit.evalue), round(hit.pvalue))
```

Otherwise I guess you're settled! :)
