### ISSUE TITLE
Uninformative error when input hmm file contains profiles with different alphabets

### ISSUE THREAD

**Issue by Sann5** [althonos/pyhmmer#70]
Assuming we have a hmm file containing profiles with different alphabets, and we run the following code:

1. Download and unzip
[amino_dna.hmm.zip](https://github.com/user-attachments/files/15612806/amino_dna.hmm.zip)

2. Open python, adjust the path to the file and run
```python
from pyhmmer.plan7 import HMMFile
fp = "path_to_the_file/amino_dna.hmm"
with HMMFile(fp) as hmm_file:
    hmm_profiles = list(hmm_file)
```

The following will raise a `TypeError` with an uninformative message. 
```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "pyhmmer/plan7.pyx", line 3563, in pyhmmer.plan7.HMMFile.__next__
  File "pyhmmer/plan7.pyx", line 3641, in pyhmmer.plan7.HMMFile.read
TypeError: an integer is required
```

It would be nice if instead, the message said something like: "Found profiles with different alphabets."

**Comment by althonos** [comment]
Actually, the error you get was raised in the code that was preparing a nicer exception message, but it had a bug and raised a `TypeError` instead. I fixed that and changed `HMMFile.read` and `HMMPressedFile.read` to raise `AlphabetMismatch` in that case, either because the file contains HMMs in multiple alphabets, or because the alphabet given to create the `HMMFile` is inconsistent with the alphabets of the HMMs in the file.
